language: node_js
node_js:
  - node
install:
  - npm install
script:
  - sh .travis/test.sh
  - sh .travis/build.sh
deploy:
  - provider: gcs
    bucket: cidc-ui-staging
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_ACCESS_KEY
    skip_cleanup: true
    acl: public-read
    on:
      branch: master
  - provider: gcs
    bucket: cidc-ui-prod
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_ACCESS_KEY
    skip_cleanup: true
    acl: public-read
    on:
      branch: production